# Generated by Django 2.1.4 on 2019-06-12 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sermon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('photo', models.FileField(upload_to='')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
