# Generated by Django 2.1.4 on 2019-06-13 21:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sermon', '0002_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='aboutEvent',
            field=models.CharField(max_length=1000),
        ),
    ]
