# Generated by Django 2.1.4 on 2019-06-13 21:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sermon', '0003_auto_20190613_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='photo',
            field=models.FileField(default=datetime.datetime(2019, 6, 13, 21, 14, 52, 449262, tzinfo=utc), upload_to=''),
            preserve_default=False,
        ),
    ]
