# Generated by Django 2.1.4 on 2019-06-13 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sermon', '0004_event_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='address',
        ),
    ]
